# 库调用

In [2]:
import numpy as np
import pandas as pd
import xarray as xr

数据格式：

1、NDArray:

在numpy中，array是一个函数，用来创建一个矩阵对象,而ndarray是该对象的类型.

2、DataFrame:

DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有行索引也有列索引，它可以被看做由series组成的字典（共用同一个索引）

3、DataArray:

是一个使用标签的多维数组，主要包含以下属性：

1. values：一个保存数组值的numpy.ndarray
2. dims: 每个坐标轴的维度名称 (例如， (‘x’, ‘y’, ‘z’))-
3. coords: 一个包含数组坐标的类似字典的容器，用来标记每个点（例如，数字，日期时间对象或字符串的一维数组）
4. attrs: 存放任意元数据（属性）的字典

# 一、文本类型文件 

文件名类型包括.txt/.csv/.asc等等，可以用记事本或其它文本编辑软件直接打开，并且内容可以直接查看。

## 文件编码

                  GB2312 -> GBK
ASCII 

                  unicode -> UTF-8
                  

读取：

ASCII文件：ASCII、GBK、UTF-8编码读取

GBK文件：GBK编码读取

UTF-8文件：UTF-8编码读取

写入：

ASCII字符串，ASCII编码写入：ASCII编码文件

ASCII字符串，GBK编码写入：ASCII编码文件

ASCII字符串，UTF-8编码写入：ASCII编码文件

非ASCII字符串，ASCII编码写入：报错

非ASCII字符串，GBK编码写入：GBK编码文件

非ASCII字符串，UTF-8编码写入：UTF-8编码文件

## 查看文件编码

Linux: file + 文件名

Windows：第三方文本编辑器查看

## 举栗子

使用函数：pandas.read_csv()

参数：
1. filepath_or_buffer：路径，也可以是URL
2. sep：指定分隔符。如果不指定参数，则会尝试使用逗号分隔，多空格可使用'\s+'
3. header：指定行数用来作为列名，数据开始行数。如果文件中没有列名，则默认为0，否则设置为None。
4. names: 用于结果的列名列表，如果数据文件中没有列标题行，就需要执行header=None。
5. false_values: 设定缺测值
6. skiprows: 设定需要跳过的行号(从前往后)
7. skipfooter : 设定需要跳过的行号(从后往前)
8. skipinitialspace: 是否忽略分隔符后的空格
9. nrows: 从前数需要读取的行号 
10. na_values: 用于替换缺测值
11. parse_dates： 解析日期
12. usecols: 返回一个数据子集，该列表中的值必须可以对应到文件中的位置（数字可以对应到指定的列）

    boolean. True -> 解析索引
    
    list of ints or names. e.g. If [1, 2, 3] -> 解析1,2,3列的值作为独立的日期列；
    
    list of lists. e.g. If [[1, 3]] -> 合并1,3列作为一个日期列使用
    
    dict, e.g. {‘foo’ : [1, 3]} -> 将1,3列合并，并给合并后的列起名为"foo"

In [3]:
data1 = pd.read_csv('/home/mw/input/moyu4302/example1.txt')
data1

19791205  60000 FLEXPART V8.2
0                            0           1           1
1                                                    1
2               0           0   122.500000       47...
3             RELEASE_TEST1                           
4        1   -3600 122.2353  47.4857  3259.2   530....
..                                                 ...
119      1 -417600  86.0785  45.2314  5324.0  1084....
120      1 -421200  85.7616  45.1802  5349.6  1090....
121      1 -424800  85.4368  45.1418  5380.3  1099....
122      1 -428400  85.1247  45.1202  5414.5  1110....
123      1 -432000  84.8144  45.1143  5450.5  1124....

[124 rows x 1 columns]

In [4]:
data2 = pd.read_csv('/home/mw/input/moyu4302/example1.txt',header=None,skiprows=5,sep='\s+',usecols=[1,2,3,4],names=['time','lon','lat','high'])
# data2
# data2.lon
# data2.lon.values

In [5]:
data3 = pd.read_csv('/home/mw/input/moyu4302/example2.txt')
data3
# data3.time

time  station     t  tmax  tmin
0   2020-03-01 00:00:00    58238   8.7  12.5   1.3
1   2020-03-01 00:00:00    58235   7.5  11.3   0.8
2   2020-03-01 00:00:00    58237   8.5  11.8   1.2
3   2020-03-02 00:00:00    58238   9.5  13.3   4.4
4   2020-03-02 00:00:00    58235   8.3  12.8   4.0
5   2020-03-02 00:00:00    58237   8.8  12.9   4.2
6   2020-03-03 00:00:00    58238  13.1  14.5  10.1
7   2020-03-03 00:00:00    58235  12.4  13.7   9.6
8   2020-03-03 00:00:00    58237  13.0  14.1  10.0
9   2020-03-04 00:00:00    58238  10.3  13.8   5.2
10  2020-03-04 00:00:00    58235   9.8  12.9   4.5
11  2020-03-04 00:00:00    58237  10.1  13.1   4.8

In [7]:
data4 = pd.read_csv('/home/mw/input/moyu4302/example2.txt', parse_dates=['time'])
data4
# data4.time

time  station     t  tmax  tmin
0  2020-03-01    58238   8.7  12.5   1.3
1  2020-03-01    58235   7.5  11.3   0.8
2  2020-03-01    58237   8.5  11.8   1.2
3  2020-03-02    58238   9.5  13.3   4.4
4  2020-03-02    58235   8.3  12.8   4.0
5  2020-03-02    58237   8.8  12.9   4.2
6  2020-03-03    58238  13.1  14.5  10.1
7  2020-03-03    58235  12.4  13.7   9.6
8  2020-03-03    58237  13.0  14.1  10.0
9  2020-03-04    58238  10.3  13.8   5.2
10 2020-03-04    58235   9.8  12.9   4.5
11 2020-03-04    58237  10.1  13.1   4.8

# 二、Excel文件

通过Pandas读取以.xlsx和.xls结尾的excel文件，读取.xlsx文件需要依赖“openpyxl”模块，.xls文件需要“xlrd”模块作为解析引擎。

安装方式如下：

conda install openpyxl

conda install xlrd

使用函数pandas.read_excel()

常用参数与pandas.read_csv()基本一致

# 三、 NetCDF文件

NetCDF文件名由.nc结尾。NetCDF文件是一种自描述的二进制数据，使用者不需要为其编写任何描述文件，也不需要提前了解数据维度等信息。使用Xarray读取nc文件需要安装“netCDF4”和“cftime”两个支持库，安装方式如下：

conda install -c conda-forge netCDF4 cftime

## 举栗子

这里我下载了NCEP/NCAR Reanalysis 1 数据集的逐月气温资料

wget -P /mnt/d/bilibili/2/sc/  ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis.derived/pressure/air.mon.mean.nc

In [9]:
dataset = xr.open_dataset('/home/mw/input/moyu1828/air.mon.mean.nc')
print(dataset)

<xarray.Dataset>
Dimensions:  (lat: 73, level: 17, lon: 144, time: 882)
Coordinates:
  * level    (level) float32 1000.0 925.0 850.0 700.0 ... 50.0 30.0 20.0 10.0
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time     (time) datetime64[ns] 1948-01-01 1948-02-01 ... 2021-06-01
Data variables:
    air      (time, level, lat, lon) float32 ...
Attributes:
    description:     Data from NCEP initialized reanalysis (4x/day).  These a...
    platform:       Model
    Conventions:    COARDS
    NCO:            20121012
    history:        Mon Jul  5 21:45:36 1999: ncrcat air.mon.mean.nc /Dataset...
    title:          monthly mean air from the NCEP Reanalysis
    dataset_title:  NCEP-NCAR Reanalysis 1
    References:     http://www.psl.noaa.gov/data/gridded/data.ncep.reanalysis...


In [22]:
air_00to20 = dataset.air.loc['2000-01-01':'2020-12-31',500,90:0,:]
print(air_00to20)
import datetime as dt
air_00to20_summer = air_00to20.loc[air_00to20.time.dt.month.isin([6,7,8])]
print(air_00to20_summer)

<xarray.DataArray 'air' (time: 252, lat: 37, lon: 144)>
array([[[-42.329994, -42.329994, ..., -42.329994, -42.329994],
        [-41.969994, -41.96    , ..., -41.97999 , -41.969994],
        ...,
        [ -5.479988,  -5.370003, ...,  -5.689995,  -5.589989],
        [ -5.419991,  -5.349998, ...,  -5.599998,  -5.510002]],

       [[-38.79    , -38.79    , ..., -38.79    , -38.79    ],
        [-38.299995, -38.269997, ..., -38.329994, -38.299995],
        ...,
        [ -6.209999,  -6.199989, ...,  -6.239998,  -6.209999],
        [ -6.199989,  -6.249992, ...,  -6.229988,  -6.18    ]],

       ...,

       [[-34.934177, -34.934177, ..., -34.934177, -34.934177],
        [-34.775013, -34.741676, ..., -34.844177, -34.809177],
        ...,
        [ -4.510849,  -4.675843, ...,  -4.292513,  -4.361677],
        [ -4.458347,  -4.620843, ...,  -4.297515,  -4.327507]],

       [[-39.638714, -39.638714, ..., -39.638714, -39.638714],
        [-39.517746, -39.533886, ..., -39.495975, -39.50324 ],
    

要注意.loc[]和[]的区别

In [23]:
a = air_00to20_summer.loc[:,:,90]
print(a)

<xarray.DataArray 'air' (time: 63, lat: 37)>
array([[-26.369987, -26.519997, -27.159996, ...,  -5.639992,  -5.749992,
         -5.739998],
       [-23.729988, -23.41999 , -22.91999 , ...,  -5.57    ,  -5.719994,
         -5.669991],
       [-25.69999 , -24.900002, -23.799995, ...,  -5.859993,  -6.019997,
         -6.010002],
       ...,
       [-26.011675, -26.640844, -26.922508, ...,  -4.750844,  -5.143346,
         -5.344175],
       [-17.366943, -17.14355 , -17.45726 , ...,  -5.250011,  -5.546784,
         -5.653231],
       [-21.283081, -20.939528, -20.587105, ...,  -4.6613  ,  -4.900814,
         -5.135494]], dtype=float32)
Coordinates:
    level    float32 500.0
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... 10.0 7.5 5.0 2.5 0.0
    lon      float32 90.0
  * time     (time) datetime64[ns] 2000-06-01 2000-07-01 ... 2020-08-01
Attributes:
    long_name:     Monthly Mean of Air temperature
    units:         degC
    precision:     2
    var_desc:      Air Temperature
    l

In [12]:
b = air_00to20_summer[:,:,90]
print(b)

<xarray.DataArray 'air' (time: 63, lat: 37)>
array([[-26.369987, -26.329994, -26.089989, ...,  -5.959999,  -6.089989,
         -6.049995],
       [-23.729988, -23.760002, -23.849998, ...,  -5.639992,  -5.30999 ,
         -5.159996],
       [-25.69999 , -25.659996, -25.629997, ...,  -5.239998,  -4.979988,
         -4.859993],
       ...,
       [-26.011675, -25.616676, -25.397512, ...,  -4.031679,  -3.978345,
         -3.90001 ],
       [-17.366943, -17.475002, -18.066942, ...,  -4.135493,  -4.220977,
         -4.30243 ],
       [-21.283081, -21.941143, -22.798393, ...,  -3.991145,  -3.817762,
         -3.762915]], dtype=float32)
Coordinates:
    level    float32 500.0
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... 10.0 7.5 5.0 2.5 0.0
    lon      float32 225.0
  * time     (time) datetime64[ns] 2000-06-01 2000-07-01 ... 2020-08-01
Attributes:
    long_name:     Monthly Mean of Air temperature
    units:         degC
    precision:     2
    var_desc:      Air Temperature
    

# GRIB文件

GRIB文件名通常以.grb、.grib、.grb2等结尾（并不绝对，比如GFS预报以预报时次作为文件后缀）。实际上GRIB文件分为GRIB1和GRIB2两个版本，但是此处暂不做区分。

Xarray支持两种GRIB的文件解析引擎：

	cfgrib：由ECMWF开发，支持Windows、Linux和macOS。对于某些非标准GRIB特征不提供支持。但是因为cfgrib是Windows上的唯一选项，所以Windows用户必须要选cfgrib作为GRIB解析引擎。


	PyNIO：由NCAR开发，来源于NCL，不支持Windows。因为底层与NCL同源，对GRIB的支持非常好，并且对NCEP使用的非标准特征有完善支持，所以在读取大部分GRIB文件时都会有良好表现。但是，PyNIO后续开发已经流产。且与库netCDF4>1.5.3版本冲突，在某些较新Python版本上大量读取时可能出现内存泄漏问题，未来Xarray可能会停止对PyNIO的支持。


In [31]:
dataset = xr.open_dataset('/home/mw/input/moyu4302/example4.grib2',engine='cfgrib')
print(dataset)

DatasetBuildError: multiple values for unique key, try re-open the file with one of:
    filter_by_keys={'typeOfLevel': 'unknown'}
    filter_by_keys={'typeOfLevel': 'surface'}
    filter_by_keys={'typeOfLevel': 'isobaricInhPa'}
    filter_by_keys={'typeOfLevel': 'meanSea'}
    filter_by_keys={'typeOfLevel': 'depthBelowLandLayer'}
    filter_by_keys={'typeOfLevel': 'heightAboveGround'}
    filter_by_keys={'typeOfLevel': 'heightAboveGroundLayer'}
    filter_by_keys={'typeOfLevel': 'tropopause'}
    filter_by_keys={'typeOfLevel': 'maxWind'}
    filter_by_keys={'typeOfLevel': 'heightAboveSea'}
    filter_by_keys={'typeOfLevel': 'isothermZero'}
    filter_by_keys={'typeOfLevel': 'pressureFromGroundLayer'}
    filter_by_keys={'typeOfLevel': 'sigmaLayer'}
    filter_by_keys={'typeOfLevel': 'sigma'}
    filter_by_keys={'typeOfLevel': 'potentialVorticity'}

In [36]:
# dataset = xr.open_dataset('/home/mw/input/moyu4302/example4.grib2',engine='cfgrib', filter_by_keys={'typeOfLevel': 'isobaricInhPa'})
dataset = xr.open_dataset('/home/mw/input/moyu4302/example4.grib2',engine='pynio')
print(dataset)

<xarray.Dataset>
Dimensions:              (lat_0: 181, lon_0: 360, lv_AMSL1: 3, lv_DBLL11: 4, lv_HTGL2: 3, lv_HTGL4: 2, lv_HTGL7: 3, lv_ISBL0: 31, lv_ISBL10: 17, lv_ISBL6: 21, lv_ISBL8: 26, lv_PVL3: 2, lv_SIGL5: 4, lv_SPDL9: 2)
Coordinates:
  * lv_ISBL10            (lv_ISBL10) float32 100.0 200.0 ... 35000.0 40000.0
  * lv_ISBL8             (lv_ISBL8) float32 1000.0 2000.0 ... 97500.0 100000.0
  * lv_HTGL7             (lv_HTGL7) float32 10.0 80.0 100.0
  * lv_ISBL6             (lv_ISBL6) float32 10000.0 15000.0 ... 97500.0 100000.0
  * lv_HTGL4             (lv_HTGL4) float32 2.0 80.0
  * lv_PVL3              (lv_PVL3) float32 -2e-06 2e-06
  * lv_HTGL2             (lv_HTGL2) float32 2.0 80.0 100.0
  * lv_AMSL1             (lv_AMSL1) float32 1829.0 2743.0 3658.0
  * lv_ISBL0             (lv_ISBL0) float32 100.0 200.0 ... 97500.0 100000.0
  * lat_0                (lat_0) float32 90.0 89.0 88.0 ... -88.0 -89.0 -90.0
  * lon_0                (lon_0) float32 0.0 1.0 2.0 3.0 ... 357.0 358.0 3

# Grads二进制文件

Grads的二进制文件名通常以.grb后缀结尾，并带有与之配套的.ctl描述文件。同时支持站点数据和网格数据。

首选建议：使用CDO转为.nc文件

cdo -f nc import_binary infile.ctl outfile.nc