# Numpy

In [2]:
import numpy as np

## ndarray

ndarray: 用于存放同种类型元素的N维数组对象，以0下标为开始进行集合元素的索引

np.array(object,dtype)

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

### Numpy 数据类型

bool_:布尔(True或者False)

int32,64:整型

float32,64:浮点型

In [66]:
a = np.array([1,2,3],dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [67]:
a = np.array([1,2,3],dtype='float32')
a

array([1., 2., 3.], dtype=float32)

### Numpy数组属性

ndarray.ndim:维数(秩)
    
ndarray.shape:维度

ndarray.size:元素总个数

ndarray.dtype:元素类型

In [73]:
a = np.array([1,2,3],dtype='int32')
a.dtype

dtype('int32')

### 创建ndarray

np.empty(shape,dtype)

np.zeros(shape,dtype)

np.ones(shape,dtype)

np.arange(start,stop,step,dtype)

np.linspace(start,stop,num,endpoint,restep,dtype)

In [81]:
a = np.arange(1,10,1)
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
b = np.array(range(1,10,1))
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
b = np.linspace(1,10,10,endpoint=True)
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### ndarray索引

通过冒号分隔切片参数索引 start:stop:step
        
为整数，包括正数和负数

In [87]:
b[1:7:2]

array([2., 4., 6.])

In [89]:
b[1:-2:2]

array([2., 4., 6., 8.])

In [94]:
b[::-1]

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

通过布尔数组索引

In [111]:
tem = np.linspace(1,10,10,endpoint=True)
tem

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [108]:
sta = np.linspace(1,50,10,endpoint=True)
sta

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [109]:
tem>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
sta[tem>5]

array([28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

### 广播(对不同shape数组进行运算)

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a*b
c

array([ 5, 12, 21, 32])

In [113]:
a = np.array([1,2,3,4])
#a = np.array([[1,2,3,4],[1,2,3,4]])

b = np.array([[5,6,7,8],[5,6,7,8]])
c = a*b
c

array([[ 5, 12, 21, 32],
       [ 5, 12, 21, 32]])

In [119]:
a = np.ones((1,2,3))
b = np.ones((3,2,3))
c = a*b
c

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

(4) * (2,4) -> (1,4) * (2,4) -> (2,4) * (2,4)

### 改变数组形状

np.reshape(array,newshape):不改变数据的条件下改变形状

np.tarnspose  (ndarray.T) :转置(对换维度)

np.swapaxes(array,axis1,axis2):交换两个轴

np.squeeze(array,axis):删除一维的轴

In [121]:
a = np.arange(1,25,1)
a.shape

(24,)

In [123]:
# b = a.reshape((2,3,4))
b = np.reshape(a,(2,3,4))
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
c = b.T
c

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [124]:
b = np.reshape(a,(2,3,4))
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [32]:
d = b.reshape((4,3,2))
d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [34]:
e = b.swapaxes(0,2)
e

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

### 拼接数组

np.concatcnate((array1,array2....),axis)

np.vstack((array1,array2....))

np.hstack((array1,array2....))

In [129]:
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6]])
c = np.array([[7,8,9],[7,8,9]])
a.shape

(2, 3)

In [133]:
d = np.concatenate((a,b,c),axis=0)
d

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [132]:
e = np.concatenate((a,b,c),axis=1)
e

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
f = np.vstack((a,b,c))
f

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [51]:
g = np.hstack((a,b,c))
g

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [134]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [135]:
d = np.concatenate((a,b),axis=0)
d

array([1, 2, 3, 4, 5, 6])

In [137]:
d = np.vstack((a,b))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
d = np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6])

### 数组元素的添加与删减

np.append(array,value,axis)

np.insert(array,obj,value,axis)

np.delete(array,obj,axis)

In [140]:
g

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [141]:
h = np.append(g,1)
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [143]:
h = np.append(g,[[1],[1]],axis=1)
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1]])

### 计算与统计函数

+,  -,  *,  /

np.power()  **

np.mod()  %,  

//

np.min()

np.max()

np.percentile()

np.mean()

np.sum()

np.std()

In [173]:
np.nanpercentile(a,95,axis=0)

7.999999999999999

In [172]:
a=np.array([1,2,3,4,np.nan,9])
a

array([ 1.,  2.,  3.,  4., nan,  9.])

In [145]:
b

array([4, 5, 6])

In [163]:
# np.power(a,2)

np.nanmean(a)

3.8

In [165]:
np.mean(a)

nan

In [174]:
a

array([ 1.,  2.,  3.,  4., nan,  9.])

In [175]:
a_norm = (a - np.nanmean(a))/np.nanstd(a)
a_norm

array([-1.00514142, -0.64616234, -0.28718326,  0.07179582,         nan,
        1.86669121])

### 排序筛选函数

np.sort(a,axis)

np.argsort()：返回函数从小到大的索引

In [179]:
a = np.array([1,3,7,4,9,2,4,6])
a_sort = np.argsort(a)
a_sort

array([0, 5, 1, 3, 6, 7, 2, 4])

In [62]:
year = np.arange(1980,1990,1)
year

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989])

In [65]:
temperature = np.random.randint(10,35,size=10)
print(temperature)

[17 24 27 19 26 24 16 20 23 21]


In [66]:
year_index = np.argsort(temperature)
year_index

array([6, 0, 3, 7, 9, 8, 1, 5, 4, 2])

In [67]:
year[year_index]

array([1986, 1980, 1983, 1987, 1989, 1988, 1981, 1985, 1984, 1982])

## 文件读写

Numpy可以读写文本数据或者二进制数据

Numpy为ndarray引入了一个简单的文件格式：.npy文件，用于存放重建ndarray数据所需的信息。

np.load(file)

np.save(file,array)

np.savez(file,array1,array2,...)

np.savetxt(file,array,fmt,delimiter)

np.loadtxt(file,dtype,delimiter)

In [68]:
np.save('/home/mw/3/year.npy',year)

In [69]:
year_tmp = np.load('/home/mw/3/year.npy')
year_tmp

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989])

In [74]:
np.savez('/home/mw/3/year&t.npz',year=year,temperature=temperature)

In [76]:
tmp = np.load('/home/mw/3/year&t.npz')
tmp.files
tmp['year']

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989])