# 1.极端事件


![Image Name](https://cdn.kesci.com/upload/image/qy9qukg195.png?imageView2/0/w/960/h/960)

![Image Name](https://cdn.kesci.com/upload/image/qy9qutjdof.png?imageView2/0/w/960/h/960)


In [5]:
import xarray as xr
import numpy as np
import datetime as dt
f_t2m = xr.open_dataset('/home/mw/input/moyu1828/t1980_2010.nc')
t2m = f_t2m.air.loc[f_t2m.time.dt.month.isin(8),39.047,120] - 273.15
t2m_array = np.array(t2m)
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)
ax.hist(t2m_array, bins=30)
plt.show()

<Figure size 432x288 with 1 Axes>

# 2.确定极端事件的分布

## 2.1极端事件指数(绝对)

In [10]:
print(t2m_array.shape)
days=0
for i in range(t2m_array.shape[0]):
    if(t2m_array[i]>28):
        days+=1
print(days)

# days = (t2m_array>28).sum()
days = np.sum(t2m_array>28)

print(days)

(961,)
12
12


In [14]:
t2m_yearly = t2m_array.reshape((31,31))
days = np.zeros((31))
for y in range(t2m_yearly.shape[0]):
    for d in range(t2m_yearly.shape[1]):
        if (t2m_yearly[y,d]>28):
            days[y]+=1
print(days)

days = (t2m_yearly>28).sum(axis=1)
print(days)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 4. 0. 1. 1. 0. 2. 0.
 0. 0. 0. 0. 0. 2. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 4 0 1 1 0 2 0 0 0 0 0 0 2 0]


## 2.2极端事件指数(相对)

In [ ]:
(31年,31天,lat,lon)
axis=1 sum,mean,max,min,std
(31年,lat,lon)



In [18]:
std = np.std(t2m_yearly,axis=0).reshape((1,31))
days = (t2m_yearly>(std+t2m_yearly.mean(axis=0).reshape((1,31)))).sum(axis=1)
days

array([ 0,  1,  0,  5,  4,  0,  0,  0,  3,  6,  2, 12,  2,  1, 18,  3,  0,
       26,  1, 10, 15,  2,  7,  0,  0,  0,  8,  8,  3, 15,  3])

In [20]:
t90 = np.percentile(t2m_yearly,90)
tx90p =  (t2m_yearly > t90).sum(axis=1)
tx90p 

array([ 0,  1,  0,  5,  2,  0,  0,  0,  2,  6,  0,  8,  1,  0, 12,  0,  0,
       19,  1,  7,  9,  1,  3,  0,  0,  0,  4,  2,  2, 10,  1])

In [21]:
tmax_yearly = np.max(t2m_yearly,axis=1)
tmax_yearly

array([25.980011, 27.309998, 26.5     , 27.399994, 27.329987, 26.230011,
       25.809998, 25.829987, 27.649994, 27.75    , 26.529999, 27.579987,
       27.110016, 26.329987, 28.380005, 26.449982, 25.899994, 28.800018,
       26.870026, 28.519989, 28.100006, 26.870026, 28.880005, 26.350006,
       26.529999, 26.579987, 27.630005, 27.029999, 27.149994, 28.279999,
       27.      ], dtype=float32)

## 2.3极端事件指数(连续事件)

In [49]:
t2m_yearly.shape
days = np.zeros((31,31))
days[t2m_yearly>26]=1

t6 = np.zeros(31)
tmp.shape
for y in range(t2m_yearly.shape[0]):
    tmp = days[y,1:] + days[y,:-1]
    if days[y,0] == 0:
        tmp = np.insert(tmp, 0, 0)
    else:
        tmp = np.insert(tmp, 0, 1)
    loc = np.arange(t2m_yearly.shape[1])
    loc = loc[tmp==1]
    dif = []
    for i in range(0, loc.shape[0], 2):
        dif.append(loc[i + 1] - loc[i])
    tmp2 = np.array(dif)
    t6[y] = tmp2[tmp2>6].sum()
print(t6)
days[9]

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  8.  0.  7.  0.  0. 11.  0.  0. 18.
  0.  8. 10.  0.  0.  0.  0.  0.  7.  0.  8. 13.  0.]


array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr = np.array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0])
tmp = arr[1:] + arr[:-1]
if arr[0] == 0:
    tmp = np.insert(tmp, 0, 0)
else:
    tmp = np.insert(tmp, 0, 1)
print(tmp)

[1 2 2 2 2 1 0 1 2 1]


# 3.确定极端事件的时间

In [50]:
f_t2m = xr.open_dataset('/home/mw/input/moyu1828/t1980_2010.nc')
t2m = f_t2m.air.loc[f_t2m.time.dt.month.isin(8),39.047,120] - 273.15
time = t2m.time

In [51]:
date = time[t2m>28]
print(date)

<xarray.DataArray 'time' (time: 12)>
array(['1994-08-12T00:00:00.000000000', '1994-08-13T00:00:00.000000000',
       '1997-08-01T00:00:00.000000000', '1997-08-05T00:00:00.000000000',
       '1997-08-06T00:00:00.000000000', '1997-08-07T00:00:00.000000000',
       '1999-08-04T00:00:00.000000000', '2000-08-01T00:00:00.000000000',
       '2002-08-01T00:00:00.000000000', '2002-08-02T00:00:00.000000000',
       '2009-08-13T00:00:00.000000000', '2009-08-14T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
    lon      float32 120.0
    lat      float32 39.047
  * time     (time) datetime64[ns] 1994-08-12 1994-08-13 ... 2009-08-14
Attributes:
    standard_name:  time
    long_name:      Time


In [58]:
from datetime import datetime, timedelta
from pandas.core.frame import DataFrame 

date = []
for y in range(t2m_yearly.shape[0]):
    for d in range(t2m_yearly.shape[1]):
        if (t2m_yearly[y,d]>28):
            date.append(datetime(year=(1980+y),month=8,day=(d+1)))

date = DataFrame({"date":date})   
print(date)

         date
0  1994-08-12
1  1994-08-13
2  1997-08-01
3  1997-08-05
4  1997-08-06
5  1997-08-07
6  1999-08-04
7  2000-08-01
8  2002-08-01
9  2002-08-02
10 2009-08-13
11 2009-08-14


In [64]:
date.date.values

array(['1994-08-12T00:00:00.000000000', '1994-08-13T00:00:00.000000000',
       '1997-08-01T00:00:00.000000000', '1997-08-05T00:00:00.000000000',
       '1997-08-06T00:00:00.000000000', '1997-08-07T00:00:00.000000000',
       '1999-08-04T00:00:00.000000000', '2000-08-01T00:00:00.000000000',
       '2002-08-01T00:00:00.000000000', '2002-08-02T00:00:00.000000000',
       '2009-08-13T00:00:00.000000000', '2009-08-14T00:00:00.000000000'],
      dtype='datetime64[ns]')