# 趋势和滤波

## 去除线性趋势

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

In [ ]:
year,lev,lat,lon
axis=0

year,lev,lat,lon
type='constant',axis=2

In [3]:
help(signal.detrend)

Help on function detrend in module scipy.signal.signaltools:

detrend(data, axis=-1, type='linear', bp=0, overwrite_data=False)
    Remove linear trend along axis from data.
    
    Parameters
    ----------
    data : array_like
        The input data.
    axis : int, optional
        The axis along which to detrend the data. By default this is the
        last axis (-1).
    type : {'linear', 'constant'}, optional
        The type of detrending. If ``type == 'linear'`` (default),
        the result of a linear least-squares fit to `data` is subtracted
        from `data`.
        If ``type == 'constant'``, only the mean of `data` is subtracted.
    bp : array_like of ints, optional
        A sequence of break points. If given, an individual linear fit is
        performed for each part of `data` between two break points.
        Break points are specified as indices into `data`.
    overwrite_data : bool, optional
        If True, perform in place detrending and avoid a copy. Defaul

In [4]:
a = np.array([15.4,14.6,15.8,14.8,15.0,15.1,15.1,15.0,15.2,15.4,
      14.8,15.0,15.1,14.7,16.0,15.7,15.4,14.5,15.1,15.3,
      15.5,15.1,15.6,15.1,15.1,14.9,15.5,15.3,15.3,15.4,
      15.7,15.2,15.5,15.5,15.6,15.1,15.1,16.0,16.0,16.8,
      16.2,16.2,16.0,15.6,15.9,16.2,16.7,15.8,16.2,15.9,
      15.8,15.5,15.9,16.8,15.5,15.8,15.0,14.9,15.3,16.0,
      16.1,16.5,15.5,15.6,16.1,15.6,16.0,15.4,15.5,15.2,
      15.4,15.6,15.1,15.8,15.5,16.0,15.2,15.8,16.2,16.2,
      15.2,15.7,16.0,16.0,15.7,15.9,15.7,16.7,15.3,16.1])

plt.figure(figsize=(10,5))
plt.plot(a,'r')
plt.show()

<Figure size 720x360 with 1 Axes>

In [7]:
a_detrend = signal.detrend(a,axis=0,type='linear')
plt.figure(figsize=(10,5))
plt.plot(a,'r')
plt.plot(a_detrend+a.mean(),'b')


<Figure size 720x360 with 1 Axes>

In [10]:
a_detrend = signal.detrend(a,axis=0,type='constant')
plt.figure(figsize=(10,5))
plt.plot(a,'r')
plt.plot(a_detrend++a.mean(),'b')

<Figure size 720x360 with 1 Axes>

In [11]:
a = np.array([15.4,14.6,15.8,14.8,15.0,15.1,15.1,15.0,15.2,15.4,
      14.8,15.0,15.1,14.7,16.0,15.7,15.4,14.5,15.1,15.3,
      15.5,15.1,15.6,15.1,15.1,14.9,15.5,15.3,15.3,15.4,
      15.7,15.2,15.5,15.5,15.6,15.1,15.1,16.0,16.0,16.8,
      16.2,16.2,16.0,15.6,15.9,16.2,16.7,15.8,16.2,15.9,
      15.8,15.5,15.9,16.8,15.5,15.8,15.0,14.9,15.3,16.0,
      16.1,16.5,15.5,15.6,16.1,15.6,16.0,15.4,15.5,15.2,
      15.4,15.6,15.1,15.8,15.5,16.0,15.2,15.8,16.2,16.2,
      15.2,15.7,16.0,16.0,15.7,15.9,15.7,16.7,15.3,16.1])

x = np.arange(45)
y1 = 0.1*x+6
y2 = -0.1*x+10
a[:45] = a[:45]+y1
a[45:] = a[45:]+y2

plt.figure(figsize=(10,5))
plt.plot(a,'r')
plt.show()

<Figure size 720x360 with 1 Axes>

In [13]:
a_detrend2 = signal.detrend(a, axis=0, type='linear', overwrite_data=False)
a_detrend = signal.detrend(a, axis=0, type='linear', bp=44, overwrite_data=False)

plt.figure(figsize=(10,5))
plt.plot(a,'r')
plt.plot(a_detrend2+a.mean(),'k')
plt.plot(a_detrend+a.mean(),'b')
plt.show()

<Figure size 720x360 with 1 Axes>

## 滤波

### 滑动平均(卷积)

In [1]:
help(np.convolve)

Help on function convolve in module numpy:

convolve(a, v, mode='full')
    Returns the discrete, linear convolution of two one-dimensional sequences.
    
    The convolution operator is often seen in signal processing, where it
    models the effect of a linear time-invariant system on a signal [1]_.  In
    probability theory, the sum of two independent random variables is
    distributed according to the convolution of their individual
    distributions.
    
    If `v` is longer than `a`, the arrays are swapped before computation.
    
    Parameters
    ----------
    a : (N,) array_like
        First one-dimensional input array.
    v : (M,) array_like
        Second one-dimensional input array.
    mode : {'full', 'valid', 'same'}, optional
        'full':
          By default, mode is 'full'.  This returns the convolution
          at each point of overlap, with an output shape of (N+M-1,). At
          the end-points of the convolution, the signals do not overlap
          co

In [21]:
np.repeat(1/9,9)

array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.11111111, 0.11111111, 0.11111111])

In [14]:
a = np.array([1,2,3])
b = np.array([0.1,0.2,0.3])#np.repeat(1/9,9)
print(np.convolve(a,b,'full'))
print(np.convolve(a,b,'same'))
print(np.convolve(a,b,'valid'))

[0.1 0.4 1.  1.2 0.9]
[0.4 1.  1.2]
[1.]


In [20]:
fig = plt.figure(figsize=(15,15))
ax1 = fig.add_axes([0.1, 0.8, 0.3, 0.1])
ax1.scatter(np.arange(3),a)
ax1.set_xlim(-2,8)
ax1.set_ylim(0,6)
ax1.set_title('a')

ax2 = fig.add_axes([0.5, 0.8, 0.3, 0.1])
ax2.scatter(np.arange(3),b)
ax2.set_xlim(-2,8)
ax2.set_ylim(0,1)
ax2.set_title('b')

ax2 = fig.add_axes([0.1, 0.65, 0.3, 0.1])
ax2.scatter(np.arange(3),a*b[0])
ax2.set_xlim(-2,8)
ax2.set_ylim(0,1)
ax2.set_title('a*b[0]')

ax2 = fig.add_axes([0.1, 0.5, 0.3, 0.1])
ax2.scatter(np.arange(1,4),a*b[1])
ax2.set_xlim(-2,8)
ax2.set_ylim(0,1)
ax2.set_title('a*b[1]')

ax2 = fig.add_axes([0.1, 0.35, 0.3, 0.1])
ax2.scatter(np.arange(2,5),a*b[2])
ax2.set_xlim(-2,8)
ax2.set_ylim(0,1)
ax2.set_title('a*b[2]')

fig.text(0.45,0.7,'0.1,0.2,0.3',fontsize=18)
fig.text(0.45,0.55,'_,0.2,0.4,0.6',fontsize=18)
fig.text(0.45,0.4,'_,_,0.3,0.6,0.9',fontsize=18)

fig.text(0.45,0.35,'0.1+_+_ = 0.1, 0.2+0.2+_=0.4,0.3+0.4+0.3=1,_+0.6+0.6=1.2,_+_+0.9=0.9',fontsize=18)

Text(0.45, 0.35, '0.1+_+_ = 0.1, 0.2+0.2+_=0.4,0.3+0.4+0.3=1,_+0.6+0.6=1.2,_+_+0.9=0.9')

<Figure size 1080x1080 with 5 Axes>

In [22]:
a = np.array([ 1.438037  ,  0.56234264,  0.3169084 ,  0.06911968,  0.5665623 ,
        1.5300182 ,  0.58640814,  0.31758106,  1.4876018 , -0.7618939 ,
        0.35573307, -0.95838505, -0.92782617, -0.5511353 ,  0.14957434,
       -1.0467534 , -0.46021378, -0.46028218, -1.4724817 , -0.06936611,
       -0.43971166,  1.8169147 , -1.605958  , -1.0131035 , -1.1547837 ,
        0.15563792, -0.25747752, -1.3881027 , -0.68700427, -0.2095188 ,
        1.7450378 ,  0.3366057 ,  0.93491715,  1.080349  ,  0.27542242,
       -1.605958  ,  1.9339806 , -0.9839922 ,  0.39519355])

plt.figure(figsize=(10,5))
plt.ylim(-3,3)
plt.axhline(0,linestyle="-",c='k')
plt.plot(a,c='k')

<Figure size 720x360 with 1 Axes>

In [23]:
a_9_valid = np.convolve(a, np.repeat(1/9, 9), mode='valid')
a_9_full = np.convolve(a, np.repeat(1/9, 9), mode='full')
a_9_same = np.convolve(a, np.repeat(1/9, 9), mode='same')

plt.figure(figsize=(10,5))
plt.ylim(-2,2)
plt.axhline(0,linestyle="-",c='k')
plt.plot(a_9_valid,c='r')
plt.plot(a_9_full,c='b')
plt.plot(a_9_same,c='g')
plt.plot(a,c='k')

plt.show()

<Figure size 720x360 with 1 Axes>

In [24]:
plt.figure(figsize=(10,5))
plt.ylim(-2,2)
plt.axhline(0,linestyle="-",c='k')
plt.plot(np.arange(-4,43),a_9_full,c='b')
plt.plot(np.arange(39),a_9_same,c='g')
plt.plot(np.arange(4,35),a_9_valid,c='r')

plt.plot(np.arange(39),a,c='k')

plt.show()

<Figure size 720x360 with 1 Axes>

### 滤波

In [6]:
help(signal.butter)

Help on function butter in module scipy.signal.filter_design:

butter(N, Wn, btype='low', analog=False, output='ba', fs=None)
    Butterworth digital and analog filter design.
    
    Design an Nth-order digital or analog Butterworth filter and return
    the filter coefficients.
    
    Parameters
    ----------
    N : int
        The order of the filter.
    Wn : array_like
        A scalar or length-2 sequence giving the critical frequencies.
        For a Butterworth filter, this is the point at which the gain
        drops to 1/sqrt(2) that of the passband (the "-3 dB point").
    
        For digital filters, `Wn` are in the same units as `fs`.  By default,
        `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
        where 1 is the Nyquist frequency.  (`Wn` is thus in
        half-cycles / sample.)
    
        For analog filters, `Wn` is an angular frequency (e.g. rad/s).
    btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
        The t

In [7]:
help(signal.filtfilt)

Help on function filtfilt in module scipy.signal.signaltools:

filtfilt(b, a, x, axis=-1, padtype='odd', padlen=None, method='pad', irlen=None)
    Apply a digital filter forward and backward to a signal.
    
    This function applies a linear digital filter twice, once forward and
    once backwards.  The combined filter has zero phase and a filter order
    twice that of the original.
    
    The function provides options for handling the edges of the signal.
    
    Parameters
    ----------
    b : (N,) array_like
        The numerator coefficient vector of the filter.
    a : (N,) array_like
        The denominator coefficient vector of the filter.  If ``a[0]``
        is not 1, then both `a` and `b` are normalized by ``a[0]``.
    x : array_like
        The array of data to be filtered.
    axis : int, optional
        The axis of `x` to which the filter is applied.
        Default is -1.
    padtype : str or None, optional
        Must be 'odd', 'even', 'constant', or None.  

In [25]:
x = np.array([ 1.438037  ,  0.56234264,  0.3169084 ,  0.06911968,  0.5665623 ,
        1.5300182 ,  0.58640814,  0.31758106,  1.4876018 , -0.7618939 ,
        0.35573307, -0.95838505, -0.92782617, -0.5511353 ,  0.14957434,
       -1.0467534 , -0.46021378, -0.46028218, -1.4724817 , -0.06936611,
       -0.43971166,  1.8169147 , -1.605958  , -1.0131035 , -1.1547837 ,
        0.15563792, -0.25747752, -1.3881027 , -0.68700427, -0.2095188 ,
        1.7450378 ,  0.3366057 ,  0.93491715,  1.080349  ,  0.27542242,
       -1.605958  ,  1.9339806 , -0.9839922 ,  0.39519355])

plt.figure(figsize=(10,5))
plt.ylim(-2,2)
plt.axhline(0,linestyle="-",c='k')
plt.plot(x,c='k')

<Figure size 720x360 with 1 Axes>

In [27]:
sample_fre = 1
nyquist_frequency = sample_fre*0.5
cutoff = 1/10
lowcut = cutoff/nyquist_frequency
cutoff = 1/3
highcut = cutoff/nyquist_frequency

In [31]:
b, a = signal.butter(2, lowcut, 'lowpass')  
x_low = signal.filtfilt(b, a, x)      

b, a = signal.butter(2, highcut, 'highpass')  
x_high = signal.filtfilt(b, a, x)  

b, a = signal.butter(2, [lowcut,highcut], 'bandpass')  
x_band = signal.filtfilt(b, a, x)  

plt.figure(figsize=(10,5))
plt.ylim(-2,2)
plt.axhline(0,linestyle="-",c='k')
plt.plot(x,c='k')
plt.plot(x_low,c='r')
plt.plot(x_high,c='b')
plt.plot(x_band,c='g')


<Figure size 720x360 with 1 Axes>