In [4]:
import numpy as np
import matplotlib.pyplot as plt
y = np.random.randn(30)   
print(y,y.shape)

y2 = y.reshape((5,6))
print(y2,y2.shape)

[-1.02978822  0.11876955  0.82095506  1.53027084  0.06659726 -0.77069295
 -0.67780527 -0.42522077 -1.30782684  0.91720779  0.43876094  0.79159781
  0.70764151 -0.94010789  0.65303201  0.64217025  0.36022361  0.28740056
 -0.13686562  0.48812791  1.92432455  0.12647248  0.81379749  0.79010952
  0.53930635 -0.01246172  0.1095334  -0.50546983  0.98522516 -0.35289026] (30,)
[[-1.02978822  0.11876955  0.82095506  1.53027084  0.06659726 -0.77069295]
 [-0.67780527 -0.42522077 -1.30782684  0.91720779  0.43876094  0.79159781]
 [ 0.70764151 -0.94010789  0.65303201  0.64217025  0.36022361  0.28740056]
 [-0.13686562  0.48812791  1.92432455  0.12647248  0.81379749  0.79010952]
 [ 0.53930635 -0.01246172  0.1095334  -0.50546983  0.98522516 -0.35289026]] (5, 6)


# 1.一维数据可视化


## 1.1折线图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.plot.html#matplotlib.axes.Axes.plot

In [7]:
fig, axs = plt.subplots(1, 1)
axs.plot(np.arange(1979,2009),y)

<Figure size 432x288 with 1 Axes>

## 1.2柱状图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar

In [8]:
fig, axs = plt.subplots(1, 1)
axs.bar(np.arange(1979,2009),y)

<BarContainer object of 30 artists>

<Figure size 432x288 with 1 Axes>

## 1.3直方图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.hist.html?highlight=hist#matplotlib.axes.Axes.hist

In [9]:
fig, axs = plt.subplots(1, 1)
axs.hist(y)

(array([2., 3., 3., 1., 6., 4., 8., 1., 1., 1.]),
 array([-1.30782684, -0.9846117 , -0.66139656, -0.33818142, -0.01496628,
         0.30824886,  0.631464  ,  0.95467914,  1.27789427,  1.60110941,
         1.92432455]),
 <a list of 10 Patch objects>)

<Figure size 432x288 with 1 Axes>

## 1.4箱线图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.boxplot.html?highlight=boxplot#matplotlib.axes.Axes.boxplot

In [10]:
fig, axs = plt.subplots(1, 1)
axs.boxplot(y)

{'whiskers': [<matplotlib.lines.Line2D at 0x7f36308eafd0>,
 'caps': [<matplotlib.lines.Line2D at 0x7f36308f96d8>,
 'boxes': [<matplotlib.lines.Line2D at 0x7f36308eacc0>],
 'medians': [<matplotlib.lines.Line2D at 0x7f36308f9d68>],
 'fliers': [<matplotlib.lines.Line2D at 0x7f36309040f0>],
 'means': []}

<Figure size 432x288 with 1 Axes>

## 1.5 散点图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter

In [12]:
x, y = np.random.rand(2, 45)
c = np.random.randint(1, 5, size=45)
print(x.shape,y.shape,c.shape)

fig, ax = plt.subplots()
ax.scatter(x, y, c=c)

(45,) (45,) (45,)


<Figure size 432x288 with 1 Axes>

# 2. 二维数据可视化

In [ ]:
【n，m】

1,2
3,4

In [13]:
x = np.arange(-3.0, 3.0, 0.2)
y = np.arange(-2.0, 2.0, 0.2)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
z = (Z1 - Z2) * 2
print(x.shape,y.shape,z.shape)

(30,) (20,) (20, 30)


## 2.1等值线图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.contour.html#matplotlib.axes.Axes.contour

In [16]:
fig, ax = plt.subplots()
c = ax.contour(x, y, z)
ax.clabel(c)

<a list of 6 text.Text objects>

<Figure size 432x288 with 1 Axes>

## 2.2填色图

In [ ]:
t,lev,lat,lon
t,lev,-5-5,lon.mean((0,2))
lev,lon

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.contourf.html?highlight=contourf#matplotlib.axes.Axes.contourf

In [20]:
fig, ax = plt.subplots()
c = ax.contourf(x, y, z)

<Figure size 432x288 with 1 Axes>

In [18]:
fig, ax = plt.subplots()
c = ax.pcolor(x, y, z)

<Figure size 432x288 with 1 Axes>

## 2.3矢量图

In [21]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0, 2 * np.pi, .2)
y = np.arange(0, 2 * np.pi, .2)
X, Y = np.meshgrid(x,y)
u = np.cos(X)
v = np.sin(Y)

print(x.shape,y.shape,u.shape,v.shape)

(32,) (32,) (32, 32) (32, 32)


https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver

In [22]:
fig1, ax1 = plt.subplots()
ax1.quiver(x, y, u, v)

<Figure size 432x288 with 1 Axes>

## 2.4流线图

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.streamplot.html#matplotlib.axes.Axes.streamplot

In [24]:
fig1, ax1 = plt.subplots()
ax1.streamplot(x, y, u, v)

<Figure size 432x288 with 1 Axes>